index:
    path: /
    methods: GET
    controller: App\Controller\UserController::index

add_user:
    path: /user/publish
    methods: POST
    controller: App\Controller\UserController::registerUser

show_user:
    path: /user/{userId}
    methods: GET
    controller: App\Controller\UserController::showUser

show_catalog:
    path: /catalog/{userId}
    methods: GET
    controller: App\Controller\StorefrontController::listPizzas

list_users:
    path: /user/list/all
    methods: GET
    controller: App\Controller\userController::listUsers